version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - '80:80' # The HTTP port
      - '8080:8080' # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events

  server:
    build: ./eurosport-backend
    ports:
      - 4444:4444

  client:
    build: eurosport-frontend/
    ports:
      - 3000:3000
    depends_on:
      - server
